//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayerWinform.ServiceEmployees {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PresentationLayerWinform.ServiceEmployees.PartTimeEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PresentationLayerWinform.ServiceEmployees.FullTimeEmployee))]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class PartTimeEmployee : PresentationLayerWinform.ServiceEmployees.Employee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HourlyRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HourlyRate {
            get {
                return this.HourlyRateField;
            }
            set {
                if ((this.HourlyRateField.Equals(value) != true)) {
                    this.HourlyRateField = value;
                    this.RaisePropertyChanged("HourlyRate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class FullTimeEmployee : PresentationLayerWinform.ServiceEmployees.Employee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceEmployees.IServiceEmployees")]
    public interface IServiceEmployees {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/AddEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/AddEmployeeResponse")]
        void AddEmployee(PresentationLayerWinform.ServiceEmployees.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/AddEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(PresentationLayerWinform.ServiceEmployees.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/DeleteEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/DeleteEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/UpdateEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/UpdateEmployeeResponse")]
        void UpdateEmployee(PresentationLayerWinform.ServiceEmployees.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/UpdateEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task UpdateEmployeeAsync(PresentationLayerWinform.ServiceEmployees.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetAllEmployees", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetAllEmployeesResponse")]
        PresentationLayerWinform.ServiceEmployees.Employee[] GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetAllEmployees", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<PresentationLayerWinform.ServiceEmployees.Employee[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetEmployeeResponse")]
        PresentationLayerWinform.ServiceEmployees.Employee GetEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetEmployee", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/GetEmployeeResponse")]
        System.Threading.Tasks.Task<PresentationLayerWinform.ServiceEmployees.Employee> GetEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/CalcPartTimeEmployeeSalar" +
            "y", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/CalcPartTimeEmployeeSalar" +
            "yResponse")]
        double CalcPartTimeEmployeeSalary(int idEmployee, int hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IServiceEmployees/CalcPartTimeEmployeeSalar" +
            "y", ReplyAction="http://Microsoft.ServiceModel.Samples/IServiceEmployees/CalcPartTimeEmployeeSalar" +
            "yResponse")]
        System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmployeesChannel : PresentationLayerWinform.ServiceEmployees.IServiceEmployees, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmployeesClient : System.ServiceModel.ClientBase<PresentationLayerWinform.ServiceEmployees.IServiceEmployees>, PresentationLayerWinform.ServiceEmployees.IServiceEmployees {
        
        public ServiceEmployeesClient() {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmployeesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddEmployee(PresentationLayerWinform.ServiceEmployees.Employee emp) {
            base.Channel.AddEmployee(emp);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(PresentationLayerWinform.ServiceEmployees.Employee emp) {
            return base.Channel.AddEmployeeAsync(emp);
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public void UpdateEmployee(PresentationLayerWinform.ServiceEmployees.Employee emp) {
            base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task UpdateEmployeeAsync(PresentationLayerWinform.ServiceEmployees.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
        
        public PresentationLayerWinform.ServiceEmployees.Employee[] GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<PresentationLayerWinform.ServiceEmployees.Employee[]> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public PresentationLayerWinform.ServiceEmployees.Employee GetEmployee(int id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<PresentationLayerWinform.ServiceEmployees.Employee> GetEmployeeAsync(int id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public double CalcPartTimeEmployeeSalary(int idEmployee, int hours) {
            return base.Channel.CalcPartTimeEmployeeSalary(idEmployee, hours);
        }
        
        public System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours) {
            return base.Channel.CalcPartTimeEmployeeSalaryAsync(idEmployee, hours);
        }
    }
}
